# Generated by Django 2.0.3 on 2018-08-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='CMS-able content.')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='product.Collection')),
            ],
            options={
                'permissions': (('view', 'Can view collection extensions'), ('edit', 'Can edit collection extensions')),
            },
        ),
    ]
